on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request.
   workflow_dispatch:
   
name: Main Workflow
jobs:
  DemoSonarCloudSCan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
            fetch-depth: 0
      - name: Run tests to generate coverage statistics
        run: |
          xcodebuild test -project macos-xcode.xcodeproj -scheme SonorCLoudProjectTests -enableCodeCoverage YES -derivedDataPath build
      - name: Collect coverage into one XML report
        run: |
          bash xccov-to-generic.sh build/Logs/Test/*.xcresult/ > generic-coverage.xml
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
            GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
              -Dsonar.organization=mandabhaskarakiranorganization
              -Dsonar.projectKey=MandaBhaskaraKiran_SonorCloudDemo
